const athletesData = [
  {
    "puesto": "1",
    "placa": 1,
    "nombre": "Heidy Adriana forero florez",
    "ciudad": "Bogotá",
    "tiempoChip": "0:45:20",
    "diff": null,
    "velProm": "13.2 km/h",
    "ritmo": "4:32 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Damas",
    "diplomaPage": 0
  },
  {
    "puesto": "2",
    "placa": 41,
    "nombre": "Marly lucero Murillo pinto",
    "ciudad": "Valle de San José",
    "tiempoChip": "0:45:22",
    "diff": "+02",
    "velProm": "13.2 km/h",
    "ritmo": "4:32 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Damas",
    "diplomaPage": 37
  },
  {
    "puesto": "3",
    "placa": 57,
    "nombre": "Sandra Lucia Franco Guerrero",
    "ciudad": "Moniquira",
    "tiempoChip": "0:45:55",
    "diff": "+35",
    "velProm": "13.0 km/h",
    "ritmo": "4:35 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Damas",
    "diplomaPage": 50
  },
  {
    "puesto": "4",
    "placa": 49,
    "nombre": "Karen Tatiana Aguirre Malagon",
    "ciudad": "Moniquira",
    "tiempoChip": "0:49:52",
    "diff": "+4:32",
    "velProm": "12.0 km/h",
    "ritmo": "4:59 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Damas",
    "diplomaPage": 44
  },
  {
    "puesto": "5",
    "placa": 50,
    "nombre": "Arlet Suarez",
    "ciudad": "carrascal                                 Bucarananga",
    "tiempoChip": "0:51:14",
    "diff": "+5:54",
    "velProm": "11.7 km/h",
    "ritmo": "5:07 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Damas",
    "diplomaPage": 45
  },
  {
    "puesto": "6",
    "placa": 51,
    "nombre": "Disbey Ariza Umaña",
    "ciudad": "San gil",
    "tiempoChip": "0:59:17",
    "diff": "+13:57",
    "velProm": "10.1 km/h",
    "ritmo": "5:55 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Damas",
    "diplomaPage": 46
  },
  {
    "puesto": "7",
    "placa": 45,
    "nombre": "Zayra Andrea Marquéz león",
    "ciudad": "San gil",
    "tiempoChip": "1:00:42",
    "diff": "+15:22",
    "velProm": "9.8 km/h",
    "ritmo": "6:04 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Damas",
    "diplomaPage": 40
  },
  {
    "puesto": "8",
    "placa": 44,
    "nombre": "Maria Alejandra Buenahora",
    "ciudad": "San Gil",
    "tiempoChip": "1:01:09",
    "diff": "+15:49",
    "velProm": "9.8 km/h",
    "ritmo": "6:06 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Damas",
    "diplomaPage": 39
  },
  {
    "puesto": "9",
    "placa": 43,
    "nombre": "Lizeth Yurani Mantilla",
    "ciudad": "Hernández                     CURITÍ",
    "tiempoChip": "1:03:22",
    "diff": "+18:02",
    "velProm": "9.4 km/h",
    "ritmo": "6:20 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Damas",
    "diplomaPage": 38
  },
  {
    "puesto": "10",
    "placa": 37,
    "nombre": "Tatiana Astrid Gómez Silva",
    "ciudad": "Duitama",
    "tiempoChip": "1:03:36",
    "diff": "+18:16",
    "velProm": "9.4 km/h",
    "ritmo": "6:21 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Damas",
    "diplomaPage": 34
  },
  {
    "puesto": "11",
    "placa": 102,
    "nombre": "Gloria Mayerly Cuartas Jurado",
    "ciudad": "Bucaramanga",
    "tiempoChip": "1:10:00",
    "diff": "+24:40",
    "velProm": "8.5 km/h",
    "ritmo": "7:00 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Damas",
    "diplomaPage": 90
  },
  {
    "puesto": "12",
    "placa": 48,
    "nombre": "Diana Carolina Cadena Garces",
    "ciudad": "Bucaramanga",
    "tiempoChip": "1:16:50",
    "diff": "+31:30",
    "velProm": "7.8 km/h",
    "ritmo": "7:41 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Damas",
    "diplomaPage": 43
  },
  {
    "puesto": "13",
    "placa": 54,
    "nombre": "Sandra Yanneth Galeano Quitian",
    "ciudad": "Barbosa",
    "tiempoChip": "1:16:50",
    "diff": "+31:30",
    "velProm": "7.8 km/h",
    "ritmo": "7:41 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Damas",
    "diplomaPage": 48
  },
  {
    "puesto": "14",
    "placa": 46,
    "nombre": "Bibian Blanco",
    "ciudad": "VILLANUEVA",
    "tiempoChip": "1:17:31",
    "diff": "+32:11",
    "velProm": "7.7 km/h",
    "ritmo": "7:45 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Damas",
    "diplomaPage": 41
  },
  {
    "puesto": "15",
    "placa": 55,
    "nombre": "Diana Yamile García quiroga",
    "ciudad": "Barbosa",
    "tiempoChip": "1:18:19",
    "diff": "+32:59",
    "velProm": "7.6 km/h",
    "ritmo": "7:49 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Damas",
    "diplomaPage": 49
  },
  {
    "puesto": "1",
    "placa": 20,
    "nombre": "Marlon Stiward Diagama Franco",
    "ciudad": "Moniquira",
    "tiempoChip": "0:39:04",
    "diff": null,
    "velProm": "15.3 km/h",
    "ritmo": "3:54 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 19
  },
  {
    "puesto": "2",
    "placa": 12,
    "nombre": "César Orlando Ortiz Roa",
    "ciudad": "Málaga",
    "tiempoChip": "0:39:24",
    "diff": "+20",
    "velProm": "15.2 km/h",
    "ritmo": "3:56 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 11
  },
  {
    "puesto": "3",
    "placa": 30,
    "nombre": "Jesús Vázquez",
    "ciudad": "MOGOTES",
    "tiempoChip": "0:39:27",
    "diff": "+23",
    "velProm": "15.2 km/h",
    "ritmo": "3:56 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 27
  },
  {
    "puesto": "4",
    "placa": 101,
    "nombre": "Ferney Castellanos Sanchez",
    "ciudad": "Bogota",
    "tiempoChip": "0:40:12",
    "diff": "+1:08",
    "velProm": "14.9 km/h",
    "ritmo": "4:01 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 89
  },
  {
    "puesto": "5",
    "placa": 28,
    "nombre": "Leonel Raúl Pinzón Pinto",
    "ciudad": "Mogotes",
    "tiempoChip": "0:41:12",
    "diff": "+2:08",
    "velProm": "14.5 km/h",
    "ritmo": "4:07 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 26
  },
  {
    "puesto": "6",
    "placa": 13,
    "nombre": "Kevin Giovanny Mejía Velasco",
    "ciudad": "Bogotá",
    "tiempoChip": "0:41:34",
    "diff": "+2:30",
    "velProm": "14.4 km/h",
    "ritmo": "4:09 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 12
  },
  {
    "puesto": "7",
    "placa": 18,
    "nombre": "Kevin David Caldera Figueroa",
    "ciudad": "San Gil",
    "tiempoChip": "0:42:09",
    "diff": "+3:05",
    "velProm": "14.2 km/h",
    "ritmo": "4:12 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 17
  },
  {
    "puesto": "8",
    "placa": 34,
    "nombre": "Henry Mauricio Monsalve",
    "ciudad": "SAN GIL",
    "tiempoChip": "0:43:15",
    "diff": "+4:11",
    "velProm": "13.8 km/h",
    "ritmo": "4:19 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 31
  },
  {
    "puesto": "9",
    "placa": 19,
    "nombre": "Andrés Felipe Pineda Pérez",
    "ciudad": "Villanueva",
    "tiempoChip": "0:44:21",
    "diff": "+5:17",
    "velProm": "13.5 km/h",
    "ritmo": "4:26 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 18
  },
  {
    "puesto": "10",
    "placa": 7,
    "nombre": "Jhon Jairo Pinto Estevez",
    "ciudad": "San Gil",
    "tiempoChip": "0:44:56",
    "diff": "+5:52",
    "velProm": "13.3 km/h",
    "ritmo": "4:29 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 6
  },
  {
    "puesto": "11",
    "placa": 6,
    "nombre": "Jorge Iván Reyes Diaz",
    "ciudad": "Villanueva-Santander",
    "tiempoChip": "0:47:51",
    "diff": "+8:47",
    "velProm": "12.5 km/h",
    "ritmo": "4:47 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 5
  },
  {
    "puesto": "12",
    "placa": 17,
    "nombre": "David Santiago Uribe Prada",
    "ciudad": "Lebrija",
    "tiempoChip": "0:48:00",
    "diff": "+8:56",
    "velProm": "12.4 km/h",
    "ritmo": "4:48 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 16
  },
  {
    "puesto": "13",
    "placa": 31,
    "nombre": "Victor Alfonso Triana Rincon",
    "ciudad": "San Gil",
    "tiempoChip": "0:48:26",
    "diff": "+9:22",
    "velProm": "12.3 km/h",
    "ritmo": "4:50 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 28
  },
  {
    "puesto": "14",
    "placa": 3,
    "nombre": "Jonathan Fernandez Gonzales",
    "ciudad": "Curití",
    "tiempoChip": "0:48:42",
    "diff": "+9:38",
    "velProm": "12.3 km/h",
    "ritmo": "4:52 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 2
  },
  {
    "puesto": "15",
    "placa": 60,
    "nombre": "David Santiago Duarte Rueda",
    "ciudad": "Sangil",
    "tiempoChip": "0:49:44",
    "diff": "+10:40",
    "velProm": "12.0 km/h",
    "ritmo": "4:58 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 53
  },
  {
    "puesto": "16",
    "placa": 4,
    "nombre": "Emmanuel Pico Carvajal",
    "ciudad": "Sangil",
    "tiempoChip": "0:49:55",
    "diff": "+10:51",
    "velProm": "12.0 km/h",
    "ritmo": "4:59 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 3
  },
  {
    "puesto": "17",
    "placa": 75,
    "nombre": "Oscar Ivan Meneses Otero",
    "ciudad": "San Gil",
    "tiempoChip": "0:51:37",
    "diff": "+12:33",
    "velProm": "11.6 km/h",
    "ritmo": "5:09 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 66
  },
  {
    "puesto": "18",
    "placa": 10,
    "nombre": "Gustavo Adolfo Rojas Fernández",
    "ciudad": "San Gil",
    "tiempoChip": "0:51:38",
    "diff": "+12:34",
    "velProm": "11.6 km/h",
    "ritmo": "5:09 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 9
  },
  {
    "puesto": "19",
    "placa": 14,
    "nombre": "Carlos Alirio Lopez ayala",
    "ciudad": "Piedecuest",
    "tiempoChip": "0:53:04",
    "diff": "+14:00",
    "velProm": "11.3 km/h",
    "ritmo": "5:18 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 13
  },
  {
    "puesto": "20",
    "placa": 33,
    "nombre": "Silverio Gomez Meza",
    "ciudad": "San Gil - Santander",
    "tiempoChip": "0:53:46",
    "diff": "+14:42",
    "velProm": "11.1 km/h",
    "ritmo": "5:22 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 30
  },
  {
    "puesto": "21",
    "placa": 59,
    "nombre": "Carlos Anres Gualdron",
    "ciudad": "San Gil",
    "tiempoChip": "0:53:50",
    "diff": "+14:46",
    "velProm": "11.1 km/h",
    "ritmo": "5:23 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 52
  },
  {
    "puesto": "22",
    "placa": 32,
    "nombre": "Javier Ricardo Gualdrón Ramirez",
    "ciudad": "Socorro",
    "tiempoChip": "0:54:37",
    "diff": "+15:33",
    "velProm": "10.9 km/h",
    "ritmo": "5:27 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 29
  },
  {
    "puesto": "23",
    "placa": 15,
    "nombre": "Delvis Esteban Cespedes Monsalve",
    "ciudad": "san gil",
    "tiempoChip": "0:54:40",
    "diff": "+15:36",
    "velProm": "10.9 km/h",
    "ritmo": "5:28 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 14
  },
  {
    "puesto": "24",
    "placa": 16,
    "nombre": "Darwin Yesid Ramirez Carreño",
    "ciudad": "San Gil",
    "tiempoChip": "0:56:12",
    "diff": "+17:08",
    "velProm": "10.6 km/h",
    "ritmo": "5:37 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 15
  },
  {
    "puesto": "25",
    "placa": 35,
    "nombre": "Jorge Alberto Celis días",
    "ciudad": "San Gil",
    "tiempoChip": "0:58:12",
    "diff": "+19:08",
    "velProm": "10.3 km/h",
    "ritmo": "5:49 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 32
  },
  {
    "puesto": "26",
    "placa": 58,
    "nombre": "Juan Sebastian Ojeda",
    "ciudad": "Sangil",
    "tiempoChip": "0:59:23",
    "diff": "+20:19",
    "velProm": "10.1 km/h",
    "ritmo": "5:56 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 51
  },
  {
    "puesto": "27",
    "placa": 11,
    "nombre": "Cesar Ivan Ramirez Gomez",
    "ciudad": "San Gil",
    "tiempoChip": "0:59:36",
    "diff": "+20:32",
    "velProm": "10.0 km/h",
    "ritmo": "5:57 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 10
  },
  {
    "puesto": "28",
    "placa": 27,
    "nombre": "Ricardo Amaya Infante",
    "ciudad": "Duitama",
    "tiempoChip": "0:59:57",
    "diff": "+20:53",
    "velProm": "10.0 km/h",
    "ritmo": "5:59 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 25
  },
  {
    "puesto": "29",
    "placa": 8,
    "nombre": "John Andres Atehotua",
    "ciudad": "Barbosa",
    "tiempoChip": "1:00:16",
    "diff": "+21:12",
    "velProm": "9.9 km/h",
    "ritmo": "6:01 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 7
  },
  {
    "puesto": "30",
    "placa": 26,
    "nombre": "Oscar Santos",
    "ciudad": "San gil",
    "tiempoChip": "1:03:36",
    "diff": "+24:32",
    "velProm": "9.4 km/h",
    "ritmo": "6:21 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 24
  },
  {
    "puesto": "31",
    "placa": 24,
    "nombre": "Fredy Alexander Ferreira Castro",
    "ciudad": "SAN GIL",
    "tiempoChip": "1:08:31",
    "diff": "+29:27",
    "velProm": "8.7 km/h",
    "ritmo": "6:51 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 23
  },
  {
    "puesto": "32",
    "placa": 23,
    "nombre": "Geovanni Garcia Ballen",
    "ciudad": "Bucaramanga",
    "tiempoChip": "1:10:17",
    "diff": "+31:13",
    "velProm": "8.5 km/h",
    "ritmo": "7:01 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 22
  },
  {
    "puesto": "33",
    "placa": 2,
    "nombre": "Emmanuel Joseph Monsalve Gelvez",
    "ciudad": "BUCARAMANGA",
    "tiempoChip": "1:12:03",
    "diff": "+32:59",
    "velProm": "8.3 km/h",
    "ritmo": "7:12 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 1
  },
  {
    "puesto": "34",
    "placa": 9,
    "nombre": "Jerónimo García Perez",
    "ciudad": "Bucaramanga",
    "tiempoChip": "1:17:31",
    "diff": "+38:27",
    "velProm": "7.7 km/h",
    "ritmo": "7:45 Min/km",
    "categoria": "10 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 8
  },
  {
    "puesto": "1",
    "placa": 82,
    "nombre": "Camila Andrea Herreño Fonseca",
    "ciudad": "Bogotá",
    "tiempoChip": "0:44:13",
    "diff": null,
    "velProm": "6.7 km/h",
    "ritmo": "8:50 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 71
  },
  {
    "puesto": "2",
    "placa": 47,
    "nombre": "Stephanie Yisela Diagama",
    "ciudad": "Moniquira",
    "tiempoChip": "0:45:45",
    "diff": "+1:32",
    "velProm": "6.5 km/h",
    "ritmo": "9:09 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 42
  },
  {
    "puesto": "3",
    "placa": 39,
    "nombre": "Dary garces",
    "ciudad": "San gil",
    "tiempoChip": "0:47:07",
    "diff": "+2:54",
    "velProm": "6.3 km/h",
    "ritmo": "9:25 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 35
  },
  {
    "puesto": "4",
    "placa": 78,
    "nombre": "Anna Lucía Ballen Herreño",
    "ciudad": "Bogotá",
    "tiempoChip": "0:47:07",
    "diff": "+2:54",
    "velProm": "6.3 km/h",
    "ritmo": "9:25 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 68
  },
  {
    "puesto": "5",
    "placa": 36,
    "nombre": "Lineth Daniela Camacho Rojas",
    "ciudad": "San gil",
    "tiempoChip": "0:47:09",
    "diff": "+2:56",
    "velProm": "6.3 km/h",
    "ritmo": "9:25 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 33
  },
  {
    "puesto": "6",
    "placa": 92,
    "nombre": "Diana Marcela Pedraza",
    "ciudad": "Piedecuesta",
    "tiempoChip": "0:47:12",
    "diff": "+2:59",
    "velProm": "6.3 km/h",
    "ritmo": "9:26 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 81
  },
  {
    "puesto": "7",
    "placa": 79,
    "nombre": "Adriana Mildred Garcia Rueda",
    "ciudad": "sangil",
    "tiempoChip": "0:47:46",
    "diff": "+3:33",
    "velProm": "6.2 km/h",
    "ritmo": "9:33 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 69
  },
  {
    "puesto": "8",
    "placa": 94,
    "nombre": "Laura Catalina Moreno Sanabria",
    "ciudad": "Barichara",
    "tiempoChip": "0:49:08",
    "diff": "+4:55",
    "velProm": "6.1 km/h",
    "ritmo": "9:49 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 83
  },
  {
    "puesto": "9",
    "placa": 40,
    "nombre": "Lizeth Fernanda Murillo pinto",
    "ciudad": "Ocamonte",
    "tiempoChip": "0:50:14",
    "diff": "+6:01",
    "velProm": "5.9 km/h",
    "ritmo": "10:02 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 36
  },
  {
    "puesto": "10",
    "placa": 85,
    "nombre": "Lorena Soto Melendez",
    "ciudad": "San Gil",
    "tiempoChip": "0:58:07",
    "diff": "+13:54",
    "velProm": "5.1 km/h",
    "ritmo": "11:37 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 74
  },
  {
    "puesto": "11",
    "placa": 52,
    "nombre": "Virgelina Lascano de Horta",
    "ciudad": "Socorro",
    "tiempoChip": "0:59:24",
    "diff": "+15:11",
    "velProm": "5.0 km/h",
    "ritmo": "11:52 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 47
  },
  {
    "puesto": "12",
    "placa": 84,
    "nombre": "Laura Lisseth Lizarazo Solano",
    "ciudad": "San Gil",
    "tiempoChip": "1:00:55",
    "diff": "+16:42",
    "velProm": "4.9 km/h",
    "ritmo": "12:11 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 73
  },
  {
    "puesto": "13",
    "placa": 81,
    "nombre": "Angie Mancera",
    "ciudad": "Pinchote",
    "tiempoChip": "1:01:51",
    "diff": "+17:38",
    "velProm": "4.8 km/h",
    "ritmo": "12:22 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 70
  },
  {
    "puesto": "14",
    "placa": 86,
    "nombre": "Sofía Leon",
    "ciudad": "San Gil",
    "tiempoChip": "1:02:01",
    "diff": "+17:48",
    "velProm": "4.8 km/h",
    "ritmo": "12:24 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 75
  },
  {
    "puesto": "15",
    "placa": 93,
    "nombre": "Yenny Patricia Silva Uribe",
    "ciudad": "San Gil",
    "tiempoChip": "1:02:06",
    "diff": "+17:53",
    "velProm": "4.8 km/h",
    "ritmo": "12:25 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 82
  },
  {
    "puesto": "16",
    "placa": 83,
    "nombre": "Claudia Molina",
    "ciudad": "Contratación Santander",
    "tiempoChip": "1:04:44",
    "diff": "+20:31",
    "velProm": "4.6 km/h",
    "ritmo": "12:56 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 72
  },
  {
    "puesto": "17",
    "placa": 88,
    "nombre": "Yuly Andrea Mendoza",
    "ciudad": "Piedecuesta",
    "tiempoChip": "1:05:20",
    "diff": "+21:07",
    "velProm": "4.5 km/h",
    "ritmo": "13:04 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 77
  },
  {
    "puesto": "18",
    "placa": 87,
    "nombre": "Gineth Martínez",
    "ciudad": "SAN GIL",
    "tiempoChip": "1:05:21",
    "diff": "+21:08",
    "velProm": "4.5 km/h",
    "ritmo": "13:04 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 76
  },
  {
    "puesto": "19",
    "placa": 91,
    "nombre": "Martha yaneth marin correa",
    "ciudad": "San gil",
    "tiempoChip": "1:05:34",
    "diff": "+21:21",
    "velProm": "4.5 km/h",
    "ritmo": "13:06 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 80
  },
  {
    "puesto": "20",
    "placa": 89,
    "nombre": "Adriana Perez Silva",
    "ciudad": "Bucaramanga",
    "tiempoChip": "1:11:33",
    "diff": "+27:20",
    "velProm": "4.1 km/h",
    "ritmo": "14:18 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 78
  },
  {
    "puesto": "21",
    "placa": 90,
    "nombre": "Ana Rosa Ballen Rozo",
    "ciudad": "Bucaramanga",
    "tiempoChip": "1:11:58",
    "diff": "+27:45",
    "velProm": "4.1 km/h",
    "ritmo": "14:23 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Damas",
    "diplomaPage": 79
  },
  {
    "puesto": "1",
    "placa": 74,
    "nombre": "Edgar Chaparro Almeida",
    "ciudad": "Los Santos",
    "tiempoChip": "0:24:13",
    "diff": null,
    "velProm": "12.3 km/h",
    "ritmo": "4:50 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 65
  },
  {
    "puesto": "2",
    "placa": 70,
    "nombre": "Edgar Olarte",
    "ciudad": "Piedecuesta",
    "tiempoChip": "0:24:16",
    "diff": "+03",
    "velProm": "12.3 km/h",
    "ritmo": "4:51 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 62
  },
  {
    "puesto": "3",
    "placa": 68,
    "nombre": "Yorby Alexis Lopez Ardila",
    "ciudad": "Barichara",
    "tiempoChip": "0:39:08",
    "diff": "+14:55",
    "velProm": "7.6 km/h",
    "ritmo": "7:49 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 60
  },
  {
    "puesto": "4",
    "placa": 77,
    "nombre": "Luis Francisco Diagama Forero",
    "ciudad": "Moniquira",
    "tiempoChip": "0:40:36",
    "diff": "+16:23",
    "velProm": "7.3 km/h",
    "ritmo": "8:07 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 67
  },
  {
    "puesto": "5",
    "placa": 5,
    "nombre": "Fabian Galvis Cardenas",
    "ciudad": "Valle de San José",
    "tiempoChip": "0:40:46",
    "diff": "+16:33",
    "velProm": "7.3 km/h",
    "ritmo": "8:09 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 4
  },
  {
    "puesto": "6",
    "placa": 22,
    "nombre": "Francisco Andres Angarita Rivera",
    "ciudad": "San gil",
    "tiempoChip": "0:40:53",
    "diff": "+16:40",
    "velProm": "7.3 km/h",
    "ritmo": "8:10 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 21
  },
  {
    "puesto": "7",
    "placa": 62,
    "nombre": "Jeyson Stick Fiaga",
    "ciudad": "San Gil",
    "tiempoChip": "0:44:48",
    "diff": "+20:35",
    "velProm": "6.6 km/h",
    "ritmo": "8:57 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 54
  },
  {
    "puesto": "8",
    "placa": 63,
    "nombre": "Anderson Jhoseth Suárez Tavera",
    "ciudad": "San Gil",
    "tiempoChip": "0:44:48",
    "diff": "+20:35",
    "velProm": "6.6 km/h",
    "ritmo": "8:57 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 55
  },
  {
    "puesto": "9",
    "placa": 67,
    "nombre": "Josué David Duarte",
    "ciudad": "San Gil",
    "tiempoChip": "0:48:33",
    "diff": "+24:20",
    "velProm": "6.1 km/h",
    "ritmo": "9:42 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 59
  },
  {
    "puesto": "10",
    "placa": 65,
    "nombre": "Keider Monsalve",
    "ciudad": "San Gil",
    "tiempoChip": "0:50:28",
    "diff": "+26:15",
    "velProm": "5.9 km/h",
    "ritmo": "10:05 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 57
  },
  {
    "puesto": "11",
    "placa": 64,
    "nombre": "Jorge Andres Rodriguez Morales",
    "ciudad": "Curiti",
    "tiempoChip": "0:52:24",
    "diff": "+28:11",
    "velProm": "5.7 km/h",
    "ritmo": "10:28 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 56
  },
  {
    "puesto": "12",
    "placa": 66,
    "nombre": "mauricio rojas rodriguez",
    "ciudad": "San Gil",
    "tiempoChip": "0:52:26",
    "diff": "+28:13",
    "velProm": "5.7 km/h",
    "ritmo": "10:29 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 58
  },
  {
    "puesto": "13",
    "placa": 103,
    "nombre": "Roque Julio Jimenez",
    "ciudad": "Aratoca",
    "tiempoChip": "0:55:45",
    "diff": "+31:32",
    "velProm": "5.3 km/h",
    "ritmo": "11:09 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 91
  },
  {
    "puesto": "14",
    "placa": 71,
    "nombre": "Cristhian Alejandro Bernal",
    "ciudad": "San Gil",
    "tiempoChip": "0:56:30",
    "diff": "+32:17",
    "velProm": "5.3 km/h",
    "ritmo": "11:18 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 63
  },
  {
    "puesto": "15",
    "placa": 21,
    "nombre": "Juan Dario Barcenas",
    "ciudad": "Contratación",
    "tiempoChip": "1:04:44",
    "diff": "+40:31",
    "velProm": "4.6 km/h",
    "ritmo": "12:56 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 20
  },
  {
    "puesto": "16",
    "placa": 73,
    "nombre": "Delgzar raul gomez pereira",
    "ciudad": "San gil",
    "tiempoChip": "1:05:25",
    "diff": "+41:12",
    "velProm": "4.5 km/h",
    "ritmo": "13:05 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 64
  },
  {
    "puesto": "17",
    "placa": 69,
    "nombre": "Anderson Rodriguez Sierra",
    "ciudad": "san gil",
    "tiempoChip": "1:07:20",
    "diff": "+43:07",
    "velProm": "4.4 km/h",
    "ritmo": "13:28 Min/km",
    "categoria": "5 K Abierta",
    "genero": "Hombres",
    "diplomaPage": 61
  },
  {
    "puesto": "1",
    "placa": 97,
    "nombre": "Erika López Araque",
    "ciudad": "San gil",
    "tiempoChip": "1:02:14",
    "diff": null,
    "velProm": "4.8 km/h",
    "ritmo": "12:26 Min/km",
    "categoria": "5 K Canicross",
    "genero": "Damas",
    "diplomaPage": 86
  },
  {
    "puesto": "2",
    "placa": 99,
    "nombre": "Verónica Balaguera",
    "ciudad": "San Gil",
    "tiempoChip": "1:10:40",
    "diff": "+8:26",
    "velProm": "4.2 km/h",
    "ritmo": "14:08 Min/km",
    "categoria": "5 K Canicross",
    "genero": "Damas",
    "diplomaPage": 88
  },
  {
    "puesto": "1",
    "placa": 98,
    "nombre": "Fabio Humberto Ruiz Moreno",
    "ciudad": "Aratoca",
    "tiempoChip": "0:40:11",
    "diff": null,
    "velProm": "7.4 km/h",
    "ritmo": "8:02 Min/km",
    "categoria": "5 K Canicross",
    "genero": "Hombres",
    "diplomaPage": 87
  },
  {
    "puesto": "2",
    "placa": 96,
    "nombre": "Naren Elver Esneyder Fiaga Díaz",
    "ciudad": "San Gil",
    "tiempoChip": "0:44:34",
    "diff": "+4:23",
    "velProm": "6.7 km/h",
    "ritmo": "8:54 Min/km",
    "categoria": "5 K Canicross",
    "genero": "Hombres",
    "diplomaPage": 85
  },
  {
    "puesto": "DNS",
    "placa": 95,
    "nombre": "Yesid Blanco",
    "ciudad": "Aratoca",
    "tiempoChip": "--",
    "diff": null,
    "velProm": null,
    "ritmo": null,
    "categoria": "5 K Canicross",
    "genero": "Hombres",
    "diplomaPage": 84
  }
];